OsamZo/hi-hello-vue

.github/workflows/deploy.yml

close #1 
<br>
<br>
- Github Actions 코드 수정

[REFACTOR] Github Actions 코드 수정

---

.github/workflows/deploy.yml

close #3 
<br>
<br>
- 깃허브 Actions 코드 변경

[REFACTOR] 깃허브 Actions 코드 변경

---

src/assets/reset.css

reset.css 추가
close #5
- reset.css 추가

[FEAT] reset.css 추가

---

src/App.vue
src/main.js
vite.config.js

close #12 
<br>
<br>
- vue 기본 설정 작업

[FEAT] vue 기본 설정 작업

---

src/components/WhiteBoxComponet.vue

close #14 
<br>
<br>
- WhiteBox 컴포넌트 생성 작업

[FEAT] WhiteBox 컴포넌트 생성 작업

---

src/main.js
src/styles/reset.css

reset.css 수정 및 main.js에 추가
close #18
- reset.css 수정(디렉토리 변경) 및 main.js에 추가

[FEAT] reset.css 수정 및 main.js에 추가

---

src/App.vue
src/components/AsideComponent.vue
src/styles/reset.css

close #17 
<br>
<br>
-  Aside 컴포넌트 구현

[FEAT] Aside 컴포넌트 구현

---

package-lock.json
package.json
src/components/Tiptap.vue
src/router/WikiRouter.js
src/router/index.js
src/services/WikiApi.js
src/views/wiki/WikiCreatePage.vue

위키 등록 페이지 에디터 및 백엔드 연동 (디자인 추후 넣을 예정)
close #9
- 위키 등록 페이지 에디터 및 백엔드 연동

[FEAT] 위키 등록 페이지 에디터 및 백엔드 연동

---

src/App.vue

close #25 
<br>
<br>
- app 페이지 섹션 분리작업

[REFACTOR] app 페이지 섹션 분리작업

---

package-lock.json
package.json
src/App.vue
src/router/UserRouter.js
src/router/index.js
src/styles/user/LoginPage.css
src/views/user/LoginPage.vue

close #22 
<br>
<br>
-  LoginPage 퍼블리싱 작업

[FEAT] LoginPage 퍼블리싱 작업

---

.github/workflows/deploy.yml
package-lock.json
package.json
src/App.vue
src/main.js
src/router/MainRouter.js
src/router/UserRouter.js
src/router/index.js
src/services/axios.js
src/stores/UserStore.js
src/views/MainPage.vue
src/views/user/LoginPage.vue

close #29
<br>
<br>
- user 로그인 관련 api연동 및 pinia 적용 작업
<br>
- baseUrl 환경 변수 처리

[FEAT] user 로그인 관련 api연동 및 pinia 적용 작업

---

src/stores/UserStore.js

로그아웃 처리 로직 수정
<br>
close #34 
<br>
<br>
- 로그아웃 처리 로직 수정
<br>
-

[CHORE] 로그아웃 처리 로직 수정

---

src/components/ListComponent.vue
src/components/WhiteBoxListComponent.vue
src/styles/reset.css

리스트 컴포넌트 구현
slot 이용해서 사용하시면 됩니다!
참고로 리스트 안에 내용 정렬(flex 같은거) 는 리스트 컴포넌트 불러쓰는 곳에서 해주세용(리스트마다 정렬방식이 다를 것 같아서)
close #38 
-  리스트 컴포넌트 구현

[FEAT] 리스트 컴포넌트 구현

---

src/stores/UserStore.js

UserStore 설정 Security 설정과 맞도록 동기화
<br>
close #36 
<br>
<br>
- UserStore 설정 Security 설정과 맞도록 동기화
<br>
-

[CHORE] UserStore 설정 Security 설정과 맞도록 동기화

---

src/stores/UserStore.js

UserStore 불필요한 설정 삭제
<br>
close #42 
<br>
<br>
- UserStore 불필요한 설정 삭제
<br>
-

[CHORE] UserStore 불필요한 설정 삭제

---

src/App.vue
src/components/AsideComponent.vue
src/components/ListComponent.vue
src/components/WhiteBoxListComponent.vue
src/router/WikiRouter.js
src/services/WikiApi.js
src/views/wiki/WikiDetailReadPage.vue
src/views/wiki/WikiListReadPage.vue

인턴위키 리스트 조회 페이지 및 상세 조회 페이지구현
close #40
- 인턴위키 리스트 조회 페이지 구현
-

[FEAT] 인턴위키 리스트 조회 및 상세조회 페이지 구현

---

src/components/WhiteBoxComponent.vue
src/styles/quiz/Quiz.css
src/views/quiz/QuizPage.vue

close #23 
<br>
<br>
- 퀴즈 페이지 스타일 리펙토링 작업
<br>
- WhiteBoxComponent 반응형 스타일링 리펙토링

[REFACTOR] 퀴즈 페이지 스타일 리펙토링 작업

---

src/services/WikiApi.js
src/views/wiki/WikiDetailReadPage.vue
src/views/wiki/WikiHistoryModal.vue
src/views/wiki/WikiUpdatePage.vue

위키 히스토리 조회 모달 구현
close #46
-  위키 히스토리 조회 모달 구현

[FEAT] 위키 히스토리 조회 모달 구현

---

src/stores/UserStore.js

jwt 토큰에서 사원 정보 추출 메서드 구현
<br>
close #54 
<br>
<br>
- jwt 토큰에서 사원 정보 추출 메서드 구현
<br>
-

[FEAT] jwt 토큰에서 사원 정보 추출 메서드 구현

---

src/stores/UserStore.js

jwt 토큰에서 사원 정보 추출이 안됨
<br>
close #58 
<br>
<br>
- jwt 토큰에서 사원 정보 추출 메서드 수정
<br>
-

[FIX] jwt 토큰에서 사원 정보 추출 메서드 수정

---

src/components/EmployeeProfile.vue

내 프로필 조회 컴포넌트 퍼블리싱 작업
<br>
close #60 
<br>
<br>
- 내 프로필 조회 컴포넌트 퍼블리싱 작업
<br>
-

[FEAT] 내 프로필 조회 컴포넌트 퍼블리싱 작업

---

src/router/TaskEvalRouter.js
src/router/index.js
src/services/TaskEvalResultApi.js
src/views/MainPage.vue
src/views/task-eval/TaskEvalListResultReadPage.vue
src/views/wiki/WikiListReadPage.vue

과제 평가 결과 리스트 페이지 구현
close #56
- 과제 평가 결과 리스트 페이지 구현

[FEAT] 과제 평가 결과 리스트 페이지 구현

---

src/components/EmployeeProfile.vue
src/components/UpdatePassword.vue

비밀번호 변경 컴포넌트 퍼블리싱
<br>
close #63 
<br>
<br>
- 비밀번호 변경 컴포넌트 퍼블리싱
<br>
- 내 프로필 조회 컴포넌트 간단한 색상 변경

[DESIGN] 비밀번호 변경 컴포넌트 퍼블리싱

---

src/views/MainPage.vue

메인페이지 테스트용 코드 삭제
close #65
- 메인페이지 테스트용 코드 삭제

[CHORE] 메인페이지 테스트용 코드 삭제

---

src/views/user/hr/EmployeeListPage.vue

사원 관리 페이지 퍼블리싱
<br>
close #67 
<br>
<br>
- 사원 관리 페이지 퍼블리싱
<br>
-

[DESIGN] 사원 관리 페이지 퍼블리싱

---

src/views/user/hr/AddEmployeePage.vue

사원 등록 페이지 퍼블리싱
<br>
close #69 
<br>
<br>
- 사원 등록 페이지 퍼블리싱
<br>
-

[DESIGN] 사원 등록 페이지 퍼블리싱

---

src/stores/QuizStore.js
src/views/quiz/QuizPage.vue
src/views/quiz/QuizResultPage.vue

close #52 
<br>
<br>
-  퀴즈 결과 페이지 api 연동 작업
<br>
- 퀴즈 페이지 api 리펙토링

[FEAT] 퀴즈 결과 페이지 api 연동 작업

---

src/styles/user/LoginPage.css
src/views/user/LoginPage.vue

close #53 
<br>
<br>
- 로그인 페이지 css 리펙토링

[REFACTOR] 로그인 페이지 css 리펙토링

---

src/components/QuizCategoryComponent.vue
src/router/QuizRouter.js
src/services/QuizApi.js
src/views/quiz/HrQuizPage.vue

close #85 
<br>
<br>
- 퀴즈 카테고리 컴포넌트 퍼블리싱 및  api 연동 작업

[FEAT] 퀴즈 카테고리 컴포넌트 퍼블리싱 및  api 연동 작업

---

src/router/TaskEvalRouter.js
src/services/TaskEvalResultApi.js
src/styles/task-eval/TaskEvalResultDetailReadPage.css
src/views/MainPage.vue
src/views/task-eval/TaskEvalResultDetailReadModal.vue
src/views/task-eval/TaskEvalResultListReadPage.vue
src/views/wiki/WikiListReadPage.vue

과제 평가 결과 상세조회 모달 구현
close #78
close #87 
- 과제 평가 결과 상세조회 모달 구현

[FEAT] 과제 평가 결과 상세조회 모달 구현

---

src/styles/quiz/HrQuiz.css
src/views/quiz/HrQuizPage.vue

close #77 
<br>
<br>
- 담당자 퀴즈 조회 페이지 퍼블리싱 작업

[FEAT] 담당자 퀴즈 조회 페이지 퍼블리싱 작업

---

src/stores/UserStore.js

로그아웃 시 로그인 화면으로 전환하도록 코드 추가
<br>
close #95 
<br>
<br>
- 로그아웃 시 로그인 화면으로 전환하도록 코드 추가
<br>
-

[CHORE] 로그아웃 시 로그인 화면으로 전환하도록 코드 추가

---

src/services/UserApi.js
src/views/user/MentorInfoPage.vue

close #101 
<br>
<br>
- 멘토 프로필 조회 api 구현

[FEAT] 멘토 프로필 조회 api 구현

---

src/router/MentoringRouter.js
src/services/MentoringApi.js
src/styles/reset.css
src/views/mentoring/MentoringPlaningListPage.vue

close #107 
<br>
- 멘토링 계획서 전체 조회, 검색 구현
<br>
-

[FEAT] 멘토링 계획서 전체 조회, 검색 구현

---

src/components/AsideComponent.vue
src/router/UserRouter.js

임시 로그아웃 버튼 구현
close #{이슈넘버}
<br>
<br>
- 임시 로그아웃 버튼 구현
<br>
-

[FEAT] 임시 로그아웃 버튼 구현

---

src/router/QuizRouter.js
src/services/QuizApi.js
src/styles/quiz/HrQuiz.css
src/views/quiz/HrQuizPage.vue

close #94
<br>
<br>
- 담당자 퀴즈 조회 api 연동 작업

[FEAT] 담당자 퀴즈 조회 api 연동 작업

---

src/services/TaskAdd.js
src/styles/task/TaskAddPage.css
src/views/task/TaskAddPage.vue

(담당자, 멘토) 과제 등록 페이지 구현
close #92 
<br>
<br>
- 
<br>
-

[FEAT] (담당자, 멘토) 과제 등록 페이지 구현

---

src/router/MentoringRouter.js
src/services/MentoringApi.js
src/styles/reset.css
src/views/mentoring/MentoringPlanningCreate.vue
src/views/mentoring/MentoringPlanningListPage.vue

close #109
<br>
<br>
-  role에 따라 멘토링 계획서 등록 버튼 보이게
- 등록 백엔드 연동
<br>
-

[FEAT] (멘토)  멘토링 계획서 등록

---

src/router/index.js
src/services/MentoringApi.js

close #125
<br>
<br>
- endpoint 변경
<br>
-

[REFACTOR] endpoint 변경

---

src/stores/UserStore.js

userStore 수정 중 및 임시 무한 루프 방지
<br>
close #128 
<br>
<br>
- userStore 수정 중 및 임시 무한 루프 방지
<br>
-

[fix] userStore 수정 중 및 임시 무한 루프 방지

---

src/router/MentoringRouter.js
src/views/mentoring/MentoringPlanningCreatePage.vue

[FIX] scoped 추가

---

src/router/MentoringRouter.js
src/services/MentoringApi.js
src/views/mentoring/MentoringPlanningCreatePage.vue
src/views/mentoring/MentoringPlanningDetailPage.vue
src/views/mentoring/MentoringPlanningListPage.vue

close #110
<br>
<br>
- 멘토링 계획서 상세 조회 백엔드 연동, 디자인
<br>
-

[FEAT] 멘토링 계획서 상세 조회

---

src/services/TaskAdd.js
src/services/TaskList.js

task기능 로직 수정
close #126 
<br>
<br>
- 
<br>
-

[CHORE] task기능 로직 수정

---

src/services/QuizApi.js
src/views/quiz/AddQuizModal.vue
src/views/quiz/HrQuizPage.vue
src/views/quiz/UpdateQuizModal.vue

close #119 
<br>
<br>
- 담당자 퀴즈 수정 기능 구현
<br>
- 퀴즈 등록 스타일 리펙토링 및 반응형 응답 리펙토링

[FEAT] 담당자 퀴즈 수정 기능 구현

---

src/services/QuizApi.js
src/views/quiz/HrQuizPage.vue

close #120 
<br>
<br>
- 담당자 퀴즈 삭제 기능 구현

[FEAT] 담당자 퀴즈 삭제 기능 구현

---

src/styles/user/LoginPage.css
src/views/user/LoginPage.vue

close #138 
<br>
<br>
- 로그인 스타일 리펙토링

[REFACTOR] 로그인 스타일 리펙토링

---

src/stores/UserStore.js

인터셉터가 정상 작동하지 않음.
<br>
close #140 
<br>
<br>
- 엑세스 토큰 만료 에러 응답을 인터셉트 하여 리프레시 토큰을 통해 a, f 토큰 재발급 후 재발급 된 a토큰으로 재 요청 및 처리, 레디스를 통한 토큰 관리 정상 확인
<br>
-

[fix] 인터셉터 정상 작동하도록 수정

---

src/components/QuizCategoryComponent.vue
src/services/QuizCategoryApi.js
src/views/quiz/HrQuizPage.vue

close #121
<br>
<br>
- 퀴즈 카테고리 삭제 기능 구현

[FEAT] 퀴즈 카테고리 삭제 기능 구현

---

src/components/QuizCategoryComponent.vue
src/stores/QuizStore.js
src/views/quiz/AddQuizCategoryModal.vue
src/views/quiz/HrQuizPage.vue
src/views/quiz/QuizPage.vue
src/views/quiz/UpdateQuizModal.vue

close #145 
<br>
<br>
- 관리자 퀴즈 관련 pinia 비활성화 작업

[REFACTOR] 관리자 퀴즈 관련 pinia 비활성화 작업

---

src/router/MentoringRouter.js
src/services/MentoringApi.js
src/views/mentoring/MentoringMatchingCreatePage.vue

close #143
<br>
<br>
-  멘토 멘티 메칭 구현
<br>
-

[FEAT] 멘토 멘티 메칭 구현

---

src/components/AsideComponent.vue
src/components/SearchBarComponent.vue
src/router/FinalEvalRouter.js
src/router/index.js
src/services/FinalEvalApi.js
src/styles/final-eval/FinaleEvalListPage.css
src/views/final-eval/FinalEvalListReadPage.vue

최종평가 리스트 조회 페이지 구현
close #89
- 최종평가 리스트 조회 페이지 구현

[FEAT] 최종평가 리스트 조회 페이지 구현

---

src/stores/UserStore.js

토큰 한글 정보 추출을 위한 디코딩 과정 수정
<br>
close #151 
<br>
<br>
- 토큰 한글 정보 추출을 위한 디코딩 과정 수정
<br>
-

[REFACTOR] 토큰 정보 추출을 위한 디코딩 과정 수정

---

src/services/FinalEvalApi.js
src/services/TaskEvalResultApi.js
src/services/WikiApi.js

axios -> springAPI
close #154
- axios -> springAPI

[CHORE] axios -> springAPI

---

src/router/FinalEvalRouter.js
src/services/FinalEvalApi.js
src/styles/final-eval/FinalEvalDetailPage.css
src/styles/final-eval/FinalEvalListPage.css
src/views/final-eval/FinalEvalDetailReadPage.vue
src/views/final-eval/FinalEvalListReadPage.vue
src/views/wiki/WikiListReadPage.vue

최종 평가 상세 조회 페이지 구현
close #150
- 최종 평가 상세 조회 페이지 구현

[FEAT] 최종 평가 상세 조회 페이지 구현

---

src/services/QuizApi.js
src/styles/quiz/QuizResult.css
src/views/quiz/HrQuizResultPage.vue

close #163 
<br>
<br>
- 담당자 퀴즈 결과 api 연동 작업

[FEAT] 담당자 퀴즈 결과 api 연동 작업

---

src/router/PeerReviewRouter.js
src/styles/peer-review/PeerReview.css
src/views/peer-review/HrPeerReviewListPage.vue
src/views/peer-review/HrPeerReviewPage.vue

close #81
<br>
<br>
- 동료 평가 조회 페이지 퍼블리싱

[FEAT] 동료 평가 조회 페이지 퍼블리싱

---

src/services/PeerReviewApi.js
src/styles/peer-review/PeerReview.css
src/views/peer-review/HrPeerReviewPage.vue

close #168
<br>
<br>
- 동료 평가 조회 api 연동 작업

[FEAT] 동료 평가 조회 api 연동 작업

---

src/components/AsideComponent.vue
src/stores/UserStore.js

aside 구성 시 과도한 userStore 호출 로직 리팩토링
<br>
close #171 
<br>
<br>
- aside 구성 시 과도한 userStore 호출하는 로직 리팩토링
<br>
-

[REFACTOR] aside 구성 시 과도한 userStore 호출 로직 리팩토링

---

src/services/OnBoarding.js
src/styles/task/TaskListPage.css
src/styles/user/MenteeOnboardingPage.css
src/views/MainPage.vue
src/views/task/TaskListPage.vue

온보딩 메인 페이지 구현
<br>
close #132 
<br>
<br>
- 
저의 최선입니다.. css로 선만 연결하면 되는데 도저히 안되네요 하하하
<br>
-

[FEAT] 온보딩 메인 페이지 구현

---

src/services/PeerReviewApi.js
src/views/peer-review/HrPeerReviewDetailModal.vue
src/views/peer-review/HrPeerReviewPage.vue

담당자 동료 평가 상세조회 기능 구현
close #170
<br>
<br>
- 담당자 동료 평가 상세조회 기능 구현

[FEAT] 담당자 동료 평가 상세조회 기능 구현

---

src/styles/task/TaskAddPage.css
src/styles/task/TaskListPage.css
src/views/task/TaskAddPage.vue

task 기능 css 코드 수정
close #176 
<br>
<br>
- 
<br>
-

[REFACTOR] task 기능 css 코드 수정

---

src/stores/UserStore.js

userStore 로그 및 주석 정리
<br>
close #175 
<br>
<br>
- userStore 로그 및 주석 정리
<br>
-

[CHORE] userStore 로그 및 주석 정리

---

src/router/TaskRouter.js
src/services/GroupingApi.js
src/services/TaskAdd.js
src/views/task/GroupingPage.vue
src/views/task/TaskAddPage.vue

close #182 
<br>
<br>
- mentee grouping 구현, 디자인
<br>
-

[FEAT] mentee grouping 구현, 디자인

---

src/router/TaskIndRouter.js
src/router/index.js
src/services/taskIndManage.js
src/styles/task-Ind/TaskIndManage.css
src/views/task-ind/TaskIndManage.vue

평가 지표 관리 페이지 구현
close #179 
<br>
<br>
- 
<br>
-

[FEAT] 평가 지표 관리 페이지 구현

---

src/router/OnboardingRouter.js
src/router/index.js
src/styles/onboarding/BreakApply.css
src/views/onboarding/BreakApplyPage.vue

close #83
<br>
<br>
- 휴가 신청 페이지 퍼블리싱

[FEAT] 휴가 신청 페이지 퍼블리싱

---

src/components/EmployeeProfile.vue
src/services/UserApi.js
src/views/user/UpdatePassword.vue
src/views/user/hr/modal/employee/DeleteEmployeeModal.vue
src/views/user/hr/modal/employee/UpdateEmployeeModal.vue
src/views/user/hr/views/employee/EmployeeListPage.vue

사원 삭제 모달 및 api 연동
<br>
close #196 
<br>
<br>
- 사원 삭제 모달 및 api 연동
<br>
-

[FEAT] 사원 삭제 모달 및 api 연동

---

package-lock.json
package.json
src/components/EditorComponent.vue
src/main.js
src/styles/task/GroupingPage.css
src/styles/wiki/EditorComponent.css
src/views/task/GroupingPage.vue
src/views/task/MentorTaskDetailReadPage.vue
src/views/wiki/WikiCreatePage.vue
src/views/wiki/WikiDetailReadPage.vue

위키 에디터 CSS 구현
close #198
- 위키 에디터 CSS 구현

[FEAT] 위키 에디터 CSS 구현

---

src/services/UserApi.js
src/views/user/hr/views/employee/AddEmployeePage.vue

사원 등록 페이지 구현 및 api 연동
<br>
close #202 
<br>
<br>
- 사원 등록 페이지 구현 및 api 연동
<br>
-

[FEAT] 사원 등록 페이지 구현 및 api 연동

---

src/services/ChatbotApi.js
src/services/axios.js
src/views/chatbot/AddChatbotCategoryModal.vue
src/views/chatbot/ChatbotCategoryComponent.vue
src/views/chatbot/HrChatbotCustomPage.vue

조회 추가 삭제 기능
close #201 
<br>
<br>
- 퀴즈 카테고리 api 연동 작업

[FEAT] 퀴즈 카테고리 api 연동 작업

---

src/services/UserApi.js
src/views/user/hr/modal/employee/UpdateEmployeeModal.vue
src/views/user/hr/views/employee/EmployeeListPage.vue

사원 정보 수정 모달 구현 및 api 연동
<br>
close #207 
<br>
<br>
- 사원 정보 수정 모달 구현 및 api 연동
<br>
-

[FEAT] 사원 정보 수정 모달 구현 및 api 연동

---

src/router/WikiRouter.js
src/services/WikiApi.js
src/styles/task/GroupingPage.css
src/styles/wiki/EditorComponent.css
src/styles/wiki/WikiUpdatePage.css
src/views/task/GroupingPage.vue
src/views/wiki/WikiCreatePage.vue
src/views/wiki/WikiDetailReadPage.vue
src/views/wiki/WikiHistoryModal.vue
src/views/wiki/WikiUpdatePage.vue

과제 상세 조회 페이지 버튼 백엔드 연동 및 특정 버전 위키 조회 구현
close #200, 210
- 과제 상세 조회 페이지 버튼 백엔드 연동 
- 특정 버전 위키 조회 구현

[FEAT] 과제 상세 조회 페이지 버튼 백엔드 연동 및 특정 버전 위키 조회 구현

---

src/services/ChatbotApi.js
src/views/chatbot/AddChatbotCategoryModal.vue
src/views/chatbot/AddChatbotModal.vue
src/views/chatbot/HrChatbotCustomPage.vue
src/views/chatbot/UpdateChatbotModal.vue

close #191 
<br>
<br>
- 챗봇 데이터 api 연동 작업

[FEAT] 챗봇 데이터 api 연동 작업

---

src/stores/UserStore.js

무한 호출 의심 코드 수정
<br>
close #213 
<br>
<br>
- userStore 인터셉터 코드 중 무한 호출 의심 코드 수정
<br>
-

[FIX] 무한 호출 의심 코드 수정

---

src/components/EditorComponent.vue
src/styles/wiki/EditorComponent.css

close #215 
<br>
<br>
- CSS 충돌
<br>
-

[FIX] CSS 충돌

---

src/services/FileApi.js
src/views/task/MentorTaskDetailReadPage.vue

파일 다운로드 메서드 구현
close #217
- 파일 다운로드 메서드 구현

[FEAT] 파일 다운로드 메서드 구현

---

src/styles/task-eval/TaskEvalResultDetailReadModal.css
src/views/task-eval/TaskEvalResultDetailReadModal.vue
src/views/task-eval/TaskEvalResultListReadPage.vue

과제 평가 상세 조회 모달 CSS 작업
close #222
- 과제 평가 상세 조회 모달 CSS 작업

[REFACTOR] 과제 평가 상세 조회 모달 CSS 작업

---

src/components/EditorComponent.vue
src/styles/task/MentorTaskDetailReadPage.css
src/views/task/MentorTaskDetailReadPage.vue

CSS 리팩토링
close #224
- CSS 리팩토링

[REFACTOR] CSS 리팩토링

---

src/services/OnboardingDataApi.js
src/styles/onboarding/OnboardingData.css
src/views/mentoring/MentoringPlanningCreatePage.vue
src/views/onboarding/OnboardingDataPage.vue

close #226
<br>
<br>
- 온보딩 퍼블리싱 완료
<br>
-

[DESIGN] 온보딩 퍼블리싱 완료

---

src/router/TaskRouter.js
src/services/MenteeTaskDetailReadPage.js
src/styles/task/MenteeTaskDetailReadPage.css
src/views/task/MenteeTaskDetailReadPage.vue

멘티 과제 제출 페이지 구현
close #205 
<br>
<br>
- 
<br>
-

[FEAT] 멘티 과제 제출 페이지 구현

---

src/components/EditorComponent.vue
src/views/wiki/WikiDetailReadPage.vue

위키 목록 생성 기능 구현
close #229
- 위키 목록 생성 기능 구현

[FEAT] 위키 목록 생성 기능 구현

---

src/views/mentoring/MentoringPlanningListPage.vue

close #233
<br>
<br>
- role 권한 수정
<br>
-

[REFACTOR] role 권한 수정

---

src/router/MentoringRouter.js
src/services/MentoringApi.js
src/views/mentoring/report/MentoringReportListPage.vue

멘토링 보고서 조회 화면 api 연동
<br>
close #236 
<br>
<br>
- 멘토링 보고서 조회 화면 api 연동
<br>
-

[FEAT] 멘토링 보고서 조회 화면 api 연동

---

src/router/MentoringRouter.js
src/services/MentoringApi.js
src/views/mentoring/report/MentoringCreateReportPage.vue

멘토링 보고서 작성 화면 api 연동
<br>
close #238 
<br>
<br>
- 멘토링 보고서 작성 화면 api 연동
<br>
-

[FEAT] 멘토링 보고서 작성 화면 api 연동

---

src/components/AsideComponent.vue
src/router/MentoringRouter.js
src/services/MentoringApi.js
src/views/mentoring/report/MentoringReportDetailPage.vue
src/views/mentoring/report/MentoringReportListPage.vue

멘토링 보고서 상세 조회 및 수정 api 연동
<br>
close #240 
<br>
<br>
- 멘토링 보고서 상세 조회 및 수정 api 연동
<br>
-

[FEAT] 멘토링 보고서 상세 조회 및 수정 api 연동

---

package-lock.json
package.json
src/router/UserRouter.js
src/router/index.js
src/stores/UserStore.js
src/stores/sse.js

멘토링 보고서 작성 시 sse를 이용한 실시간 알림 전송 구현
멘티가 멘토링 보고서 작성 시 해당 멘토에게 실시간 알림 전송
<br>
close #243 
<br>
<br>
- 멘토링 보고서 작성 시 sse를 이용한 실시간 알림 전송 구현
<br>
-

[FEAT] 멘토링 보고서 작성 시 sse를 이용한 실시간 알림 전송 구현

---

src/App.vue
src/components/AsideComponent.vue
src/components/EmployeeProfile.vue
src/stores/sse.js

aside 모달 작동 이상: 이벤트 처리 리팩토링
<br>
close #245 
<br>
<br>
- aside 이벤트 처리 리팩토링
<br>
-

[REFACTOR] aside 모달 작동 이상: 이벤트 처리 리팩토링

---

src/stores/UserStore.js

userStore 리팩토링
<br>
close #247 
<br>
<br>
- userStore 리팩토링
<br>
-

[FIX] userStore 리팩토링

---

src/components/AsideComponent.vue
src/services/MentoringApi.js
src/services/axios.js

새로 고침 시 사이드바 상태 초기화 증상 조치 완료
<br>
close #249 
<br>
<br>
- 새로 고침 시 상태 초기화 증상 조치 완료
<br>
-

[FIX] 새로 고침 시 상태 초기화 증상 임시 조치

---

src/stores/UserStore.js

엑세스 토큰 만료 후 sse 재 연결 시 무한 호출 증상 조치
<br>
close #251 
<br>
<br>
- 인터셉테 요청 설정 추가
<br>
-

[FIX] 엑세스 토큰 만료 후 sse 재 연결 시 무한 호출 증상 조치

---

src/stores/UserStore.js
src/stores/sse.js

엑세스 토큰 만료 후 sse 재 연결 시 무한 루프 증상 조치 완료
close #{이슈넘버}
<br>
<br>
- 연결 요청 전 유효성 검사 진행하도록 코드 수정
<br>
-

[FIX] 엑세스 토큰 만료 후 sse 재 연결 시 무한 루프 증상 조치 완료

---

src/router/PeerReviewRouter.js
src/router/TaskRouter.js
src/services/OnBoardingAPI.js
src/styles/onboarding/OnboardingData.css
src/views/onboarding/MainPage.vue
src/views/peer-review/GroupEval.vue

온보딩 리스트 조회 로직 수정
<br>
close #256 
<br>
<br>
- 
<br>
-

[REFACTOR] 온보딩 리스트 조회 로직 수정

---

src/components/SearchBarComponent.vue
src/services/WikiApi.js
src/views/wiki/WikiListReadPage.vue

위키 검색 관련 프론트 구현
close #258
- 위키 검색 관련 프론트 구현

[FEAT] 위키 검색 관련 프론트 구현

---

src/components/AlarmModal.vue
src/components/AsideComponent.vue
src/services/AlramApi.js
src/stores/UserStore.js
src/views/mentoring/report/MentoringReportDetailPage.vue

알림창 퍼블리싱 및 api 연동
<br>
close #260 
<br>
<br>
- 알림창 퍼블리싱 및 api 연동
<br>
-

[FEAT] 알림창 퍼블리싱 및 api 연동

---

src/App.vue
src/components/AddTask.vue
src/components/DeleteModalComponent.vue
src/components/UserRollRectangle.vue
src/services/MenteeTaskDetailReadApi.js
src/services/TaskAddApi.js
src/services/TaskListApi.js
src/services/TaskModifyApi.js
src/styles/peer-review/GroupEval.css
src/styles/task-Ind/TaskIndManage.css
src/styles/task/MenteeTaskDetailReadPage.css
src/styles/task/TaskAddPage.css
src/styles/task/TaskListPage.css
src/styles/task/TaskModifyPage.css
src/views/task/TaskAddPage.vue
src/views/task/TaskListPage.vue
src/views/task/TaskModifyPage.vue

task css 수정
<br>
close #263 
<br>
<br>
- 
<br>
-

[CHORE] task css 수정

---

src/App.vue
src/styles/onboarding/OnboardingData.css
src/styles/user/MenteeOnboardingPage.css
src/views/onboarding/MainPage.vue

온보딩 메인 화면 구현
close #262
- 온보딩 메인 화면 구현

[FEAT] 온보딩 메인 화면 구현

---

src/App.vue
src/components/AsideComponent.vue
src/stores/sse.js

알림창 디테일 작업
close #{이슈넘버}
<br>
<br>
- 알람창, 프로필 창, 서브 메뉴 창 동시에 띄워져 겹치지 않도록 구현
- 외부 클릭 시 모달창 close 하도록 구현
- 라우팅 시 모달창 close 하도록 구현
<br>
- 알림 관련 피니아 간단한 수정

[REFACTOR] 알림창 디테일 작업

---

src/services/MentoringApi.js
src/views/mentoring/MentoringPlanningDetailPage.vue

계획서 처리 로직 리팩토링
<br>
close #269 
<br>
<br>
- 계획서 처리 로직 리팩토링
- 
<br>
- api 호출 엔드포인트 수정
- 승인, 반려 버튼 v-if 조건식 수정

[REFACTOR] 계획서 처리 로직 리팩토링

---

src/App.vue
src/services/TaskAddApi.js
src/services/TaskModifyApi.js
src/styles/task-Ind/TaskIndManage.css
src/styles/task/MenteeTaskDetailReadPage.css
src/styles/task/TaskAddPage.css
src/styles/task/TaskModifyPage.css
src/views/task/TaskAddPage.vue
src/views/task/TaskModifyPage.vue

task css 수정 2차
close #268 
<br>
<br>
- 
<br>
-

[CHORE] task css 수정 2차

---

src/App.vue
src/styles/onboarding/OnboardingData.css
src/styles/user/MenteeOnboardingPage.css

온보딩 메인 페이지 모달 디자인
close #272
- 온보딩 메인 페이지 모달 디자인

[FEAT] 온보딩 메인 페이지 모달 디자인

---

package-lock.json
package.json
src/App.vue
src/components/ChatModal.vue
src/router/ChatRouter.js
src/router/index.js
src/services/ChatApi.js
src/stores/ChatStore.js
src/stores/WebSocketStore.js
src/views/chat/Chatting.vue
vite.config.js

close #33
<br>
<br>
- 채팅 연동
<br>
-

[FEAT] 채팅 연동

---

src/styles/user/MenteeOnboardingPage.css
src/views/onboarding/MainPage.vue

온보딩 박스 기본 위치 지정
close #276
- 온보딩 박스 기본 위치 지정

[FEAT] 온보딩 박스 기본 위치 지정

---

src/stores/sse.js

sse 연결 로직 리팩토링
<br>
close #279 
<br>
<br>
- sse 연결 로직 리팩토링
<br>
-

[REFACTOR] sse 연결 로직 리팩토링

---

package-lock.json
package.json
src/router/OnboardingRouter.js
src/styles/onboarding/OnboardingConferenceRoom.css
src/styles/reset.css
src/styles/task-Ind/TaskIndManage.css
src/views/onboarding/ConferenceRoomPage.vue

회의실 예약 기능 구현
close #281 
<br>
<br>
- 
<br>
-

[FEAT] 회의실 예약 기능 구현

---

src/components/AsideComponent.vue
src/services/OnBoardingAPI.js
src/styles/reset.css
src/styles/user/MenteeOnboardingPage.css
src/views/onboarding/MainPage.vue

온보딩 관련 기능 구현 및 리팩토링
close #284 #285 #286 #287
- 체크리스트 CSS 수정
- 온보딩 수행 상태 변경 구현
- 권한별 온보딩 메인페이지 API 분리
- 네비게이션바에 멘티 소개 추가

[REFACTOR] 온보딩 관련 기능 구현 및 리팩토링

---

package-lock.json
src/services/OnBoardingAPI.js
src/styles/user/MenteeOnboardingPage.css
src/views/onboarding/BreakApplyPage.vue
src/views/onboarding/ConferenceRoomPage.vue
src/views/onboarding/MainPage.vue

Onboarding 템플릿 리팩토링 2차
퀴즈, 휴가, 회의실 기능 연결
+) 휴가, 회의실 실습 완료 시 해당 템플릿 완료 처리 기능 추가
close #289 
<br>
<br>
- 
<br>
-

[REFACTOR] Onboarding 템플릿 리팩토링 2차

---

src/views/task/TaskListPage.vue

taskList -> Modify 연결
close #291 
<br>
<br>
- 
<br>
-

[REFACTOR] taskList -> Modify 연결

---

src/App.vue
src/components/ChatBotModal.vue

챗봇 페이지 연결, 슬라이딩 모션 추가
추후 챗봇 페이지 연결해야함 링크를 다른거 달아놈
close #293 
<br>
<br>
- 
<br>
-

[REFACTOR] 챗봇 페이지 연결, 슬라이딩 모션 추가

---

src/components/AsideComponent.vue

메뉴바 과제 관리 수정
<br>
close #295
<br>
<br>
- 
<br>
-

[REFACTOR] 메뉴바 과제 관리 수정

---

src/services/GroupingApi.js
src/styles/task-eval/TaskEvalResultDetailReadModal.css
src/views/task-eval/TaskEvalResultDetailReadModal.vue
src/views/task-eval/TaskEvalResultGroupMembersReadModal.vue

그룹 멤버 조회 모달 구현
close #298
- 그룹 멤버 조회 모달 구현

[FEAT] 그룹 멤버 조회 모달 구현

---

src/services/OnBoardingAPI.js
src/views/onboarding/MainPage.vue

온보딩 메인페이지 멘토 수행 완료 에러 해결
close #300
- 온보딩 메인페이지 멘토 수행 완료 에러 해결

[FIX] 온보딩 메인페이지 멘토 수행 완료 에러 해결

---

src/components/ChatModal.vue
src/services/ChatApi.js
src/views/chat/Chatting.vue

close #302 
<br>
<br>
- 멘토링 채팅 디자인
<br>
-

[DESIGN] 멘토링 채팅 디자인

---

src/services/OnBoardingAPI.js
src/styles/user/MenteeOnboardingPage.css
src/views/onboarding/MainPage.vue

메인화면 리팩토링 3차
<br>
close #297 
<br>
<br>
- 
<br>
-

[REFACTOR] 메인화면 리팩토링 3차

---

src/services/OnBoardingAPI.js
src/views/onboarding/MainPage.vue

체크리스트 모두 체크 시 온보딩 수행 완료되도록 구현
close #305
- 체크리스트 모두 체크 시 온보딩 수행 완료되도록 구현

[FEAT] 체크리스트 모두 체크 시 온보딩 수행 완료되도록 구현

---

src/styles/onboarding/OnboardingConferenceRoom.css
src/views/onboarding/ConferenceRoomPage.vue

회의실 예약 css 간섭 해결
<br>
close #307 
<br>
<br>
- 
<br>
-

[CHORE] 회의실 예약 css 간섭 해결

---

src/App.vue
src/components/ChatBotModal.vue
src/services/TaskModifyApi.js
src/views/onboarding/MainPage.vue
src/views/task/TaskModifyPage.vue

과제 수정 로직 수정
<br>
close #309 
<br>
<br>
- 
<br>
-

[CHORE] 과제 수정 로직 수정

---

src/router/QuizRouter.js
src/styles/user/MenteeOnboardingPage.css
src/views/onboarding/MainPage.vue

퀴즈 라우팅 수정
<br>
close #311 
<br>
<br>
- 
<br>
-

[CHORE] 퀴즈 라우팅 수정

---

src/App.vue
src/components/ChatModal.vue
src/services/ChatApi.js
src/views/chat/Chatting.vue

close #313
<br>
<br>
-  채팅 리스트 조회
<br>
-

[FEAT] 채팅 리스트 조회

---

src/components/EditorComponent.vue
src/services/OnBoardingAPI.js
src/styles/reset.css
src/views/onboarding/MainPage.vue

체크리스트 및 에디터 관련 오류 해결
close #316, close #317
- 체크리스트 및 에디터 관련 오류 해결

[FIX] 체크리스트 및 에디터 관련 오류 해결

---

src/views/user/hr/modal/employee/DeleteEmployeeModal.vue
src/views/user/hr/modal/employee/UpdateEmployeeModal.vue
src/views/user/hr/views/employee/EmployeeListPage.vue

사원 관리 페이지 CSS 수정
<br>
close #318 
<br>
<br>
- 사원 관리 페이지 모달 css 수정
<br>
-

[CHORE] 사원 관리 페이지 CSS 수정

---

src/components/AlarmModal.vue
src/components/AsideComponent.vue
src/views/mentoring/report/MentoringCreateReportPage.vue
src/views/mentoring/report/MentoringReportDetailPage.vue
src/views/mentoring/report/MentoringReportListPage.vue

보고서 관련 페이지 및 알람 모달 css 수정
<br>
close #320 
<br>
<br>
- 보고서 관련 페이지 및 알람 모달 css 수정
<br>
-

[CHORE] 보고서 관련 페이지 및 알람 모달 css 수정

---

src/styles/user/MenteeOnboardingPage.css
src/views/onboarding/MainPage.vue

로컬 스토리지에 boxPosition 빈 배열로 들어있을 때 초기화 로직 수정
close #322
- 로컬 스토리지에 boxPosition 빈 배열로 들어있을 때 초기화 로직 수정

[FEAT] 로컬 스토리지에 boxPosition 빈 배열로 들어있을 때 초기화 로직 수정

---

src/components/AsideComponent.vue

close #324
<br>
<br>
-  aside 수정
<br>
-

[REFACTOR] aside 수정

---

src/views/wiki/WikiCreatePage.vue
src/views/wiki/WikiDetailReadPage.vue
src/views/wiki/WikiHistoryModal.vue
src/views/wiki/WikiUpdatePage.vue

위키 관련 개선점 리팩토링
close #326
- 위키 조회 페이지 히스토리 모달 위치
- 위키 작성 및 수정 후 위키 상세 조회 페이지로 라우팅

[REFACTOR] 위키 관련 개선점 리팩토링

---

src/views/mentoring/MentoringPlanningCreatePage.vue
src/views/mentoring/MentoringPlanningDetailPage.vue
src/views/mentoring/MentoringPlanningListPage.vue

close #{이슈넘버}
<br>
<br>
1. 멘토링 계획서 메뉴 접근 시 alert 창 삭제
2. 멘토링 계획서 상세 조회 이후 뒤로 가기 시 alert 창 삭제
3. 멘토링 게획서 작성 화면 css 디테일 추가 작업  (+ 취소 or 뒤로가기 버튼)
4. 멘토링 계획서 등록 버튼 아이콘 깨짐 수정
<br>
-

[REFACTOR] 멘토링 보고서 관련 수정

---

src/services/OnboardingDataApi.js
src/styles/onboarding/OnboardingData.css
src/views/onboarding/OnboardingDataPage.vue

close #331
<br>
<br>
- 온보딩 설계 수정
<br>
-

[REFACTOR] 온보딩 설계 수정

---

src/components/AlarmModal.vue
src/components/AsideComponent.vue
src/views/user/hr/views/employee/EmployeeListPage.vue

알림, 사원 관련 css 디테일 수정
<br>
close #332 
<br>
<br>
- 알림, 사원 관련 css 디테일 수정
<br>
-

[CHORE] 알림, 사원 관련 css 디테일 수정

---

src/components/AddTask.vue
src/components/DeleteModalComponent.vue
src/services/TaskAddApi.js
src/services/TaskModifyApi.js
src/styles/onboarding/OnboardingConferenceRoom.css
src/styles/reset.css
src/styles/task/TaskAddPage.css
src/styles/task/TaskListPage.css
src/styles/task/TaskModifyPage.css
src/views/task/TaskAddPage.vue
src/views/task/TaskModifyPage.vue

과제 전체 수정
<br>
close #328 
<br>
<br>
- 
<br>
-

[REFACTOR] 과제 전체 수정

---

src/components/ListComponent.vue
src/views/mentoring/report/MentoringCreateReportPage.vue
src/views/mentoring/report/MentoringReportDetailPage.vue
src/views/mentoring/report/MentoringReportListPage.vue
src/views/user/hr/views/employee/AddEmployeePage.vue
src/views/user/hr/views/employee/EmployeeListPage.vue

사원, 멘토링 보고서 관련 페이지 버튼 통일 및 css 디테일 수정
<br>
close #336 
<br>
<br>
- 사원, 멘토링 보고서 관련 페이지 버튼 통일 및 css 디테일 수정
<br>
-

[CHORE] 사원, 멘토링 보고서 관련 페이지 버튼 통일 및 css 디테일 수정

---

src/styles/task-Ind/TaskIndManage.css

평가지표 CSS 수정
<br>
close #340 
<br>
<br>
- 
<br>
-

[CHORE] 평가지표 CSS 수정

---

src/components/AsideComponent.vue

aside 파일 내 요청 설정 코드 추가
close #{이슈넘버}
<br>
<br>
- aside 파일 내 요청 설정 코드 추가
<br>
-

[REFACTOR] 요청 설정 코드 추가

---

src/router/QuizRouter.js
src/views/quiz/QuizPage.vue
src/views/quiz/QuizResultPage.vue

close #344
<br>
<br>
- 퀴즈 api 호출 리펙토링

[REFACTOR] 퀴즈 api 호출 리펙토링

---

src/styles/onboarding/OnboardingData.css
src/views/onboarding/OnboardingDataPage.vue

close #346
<br>
<br>
- 온보딩 설계 체크리스트 수정
<br>
-

[REFACOTR] 온보딩 설계 체크리스트 수정

---

src/styles/onboarding/OnboardingData.css

close #349 
<br>
<br>
-  온보딩 설계 디자인 수정
<br>
-

[REFACTOR] 온보딩 설계 디자인 수정

---

src/styles/task/TaskAddPage.css

버튼 색상 변경 task-add
<br>
close #351 
<br>
<br>
- 
<br>
-

[CHORE] 버튼 색상 변경 task-add

---

src/views/wiki/WikiCreatePage.vue
src/views/wiki/WikiDetailReadPage.vue

위키 뒤로가기 버튼 생성
close #357
- 위키 뒤로가기 버튼 생성

[FEAT] 위키 뒤로가기 버튼 생성

---

src/components/EditorComponent.vue
src/styles/final-eval/FinalEvalDetailPage.css
src/styles/final-eval/FinalEvalListPage.css
src/styles/onboarding/OnboardingData.css
src/styles/task/MentorTaskDetailReadPage.css
src/views/final-eval/FinalEvalDetailReadPage.vue
src/views/final-eval/FinalEvalListReadPage.vue
src/views/task-eval/TaskEvalResultDetailReadModal.vue
src/views/task-eval/TaskEvalResultListReadPage.vue
src/views/wiki/WikiDetailReadPage.vue
src/views/wiki/WikiHistoryModal.vue
src/views/wiki/WikiListReadPage.vue

버튼 색상 변경 및 그룹과제일 경우에만 그룹 조회 가능하도록 리팩토링
close #354
- 버튼 색상 변경 
- 그룹과제일 경우에만 그룹 조회 가능하도록 리팩토링

[REFACTOR] 버튼 색상 변경 및 그룹과제일 경우에만 그룹 조회 가능하도록 리팩토링

---

src/components/AsideComponent.vue
src/services/OnboardingDataApi.js
src/views/onboarding/OnboardingDataPage.vue

온보딩 설계, aside 수정
close #{이슈넘버}
<br>
<br>
- 
<br>
-

[CHORE] 온보딩 설계, aside 수정

---

src/components/AsideComponent.vue
src/styles/user/MenteeOnboardingPage.css
src/views/onboarding/MainPage.vue

온보딩 메인 화면 리팩토링
close #364
- 온보딩 박스 위치 동적으로 초기화
- 온보딩 템플릿 박스 경계 밖으로 넘어가지 않도록 구현
- 모든 페이지에서 aside width 일정하도록 리팩토링

[REFACTOR] 온보딩 메인 화면 리팩토링

---

src/components/ChatModal.vue
src/services/GroupingApi.js
src/views/chat/Chatting.vue

close #369 
<br>
<br>
- 채팅 endpoint env처리
- 이전 채팅 내역 불러지는 로직 수정
<br>
-

[REFACTOR] 채팅 관련 수정

---

src/services/GroupingApi.js
src/services/TaskAddApi.js
src/views/task/GroupingPage.vue
src/views/task/TaskAddPage.vue

taskAdd 로직 수정
<br>
close #367 
<br>
<br>
- 
<br>
-

[CHORE] taskAdd 로직 수정

---

.github/workflows/deploy.yml

[REFACTOR] deploy 수정

---

src/router/index.js
src/views/user/LoginPage.vue

권한별 로그인 후 라우팅 처리
close #374
- 권한별 로그인 후 라우팅 처리

[FEAT] 권한별 로그인 후 라우팅 처리

---

src/App.vue

웹 브라우저 종료 시 로컬 스토리지 내의 토큰 제거
<br>
close #377 
<br>
<br>
- 웹 브라우저 종료 시 로컬 스토리지 내의 토큰 제거 로직 추가
<br>
-

[REFACTOR] 웹브라우저 종료 시 로컬 스토리지 내의 토큰 제거

---

src/styles/user/MenteeOnboardingPage.css
src/views/onboarding/MainPage.vue

온보딩 템플릿 드래그 시 위치 오류 해결
close #376
- 온보딩 템플릿 드래그 시 위치 오류 해결

[FIX] 온보딩 템플릿 드래그 시 위치 오류 해결

---

.github/workflows/deploy.yml

[TEST] 배포 테스트

---

src/components/AsideComponent.vue

Aside 리팩토링
close #382
- Aside 리팩토링

[REFACTOR] Aside 리팩토링

---

src/App.vue

url 수정
close #384 
<br>
<br>
- 
<br>
-

[CHORE] url 수정

---

src/App.vue

앱 언마운트시 토큰 제거 로직 삭제
<br>
close #386 
<br>
<br>
- 앱 언마운트시 토큰 제거 로직 삭제
<br>
-

[FIX] 앱 언마운트시 토큰 제거 로직 삭제

---

src/services/OnBoardingAPI.js
src/styles/wiki/EditorComponent.css
src/views/onboarding/MainPage.vue

체크리스트-온보딩 수행 상태 변경 에러 해결
close #388
- 체크리스트-온보딩 수행 상태 변경 에러 해결

[FIX] 체크리스트-온보딩 수행 상태 변경 에러 해결

---

src/views/mentoring/report/MentoringReportDetailPage.vue
src/views/user/hr/modal/employee/DeleteEmployeeModal.vue

보고서 상세 조회 화면 뒤로가기 버튼 추가
<br>
close #390 
<br>
<br>
- 보고서 상세 조회 화면 뒤로가기 버튼 추가
<br>
- 회원 삭제 모달 사이즈 수정

[CHORE] 보고서 상세 조회 화면 뒤로가기 버튼 추가

---

src/services/OnboardingDataApi.js
src/services/TaskAddApi.js
src/views/chat/Chatting.vue
src/views/onboarding/OnboardingDataPage.vue
src/views/task/GroupingPage.vue

close #392
<br>
<br>
- 과제 등록 로직 수정
- 체팅 내역 중복 오류 수정
<br>
-

[REFACTOR] 과제 등록 로직 수정

---

src/App.vue
src/components/EmployeeProfile.vue
src/services/FileApi.js
src/services/MenteeTaskDetailReadApi.js
src/styles/peer-review/PeerReviewList.css
src/styles/task-Ind/TaskIndManage.css
src/styles/task-eval/TaskEvalResultDetailReadModal.css
src/styles/task/TaskAddPage.css
src/styles/task/TaskListPage.css
src/styles/user/MenteeOnboardingPage.css
src/views/onboarding/MainPage.vue
src/views/peer-review/HrPeerReviewListPage.vue
src/views/task-ind/TaskIndManage.vue
src/views/task/MenteeTaskDetailReadPage.vue
src/views/task/MentorTaskDetailReadPage.vue
src/views/task/TaskAddPage.vue
src/views/task/TaskListPage.vue

오류 로직, CSS 수정
<br>
close #396 
<br>
<br>
- 
<br>
-

[FIX] 오류 로직, CSS 수정

---

src/components/AlarmModal.vue
src/components/AsideComponent.vue
src/services/AlramApi.js
src/stores/NotificationStore.js
src/views/user/hr/views/employee/EmployeeListPage.vue

읽지 않은 알림 개수 조회 api 연동 및 퍼블리싱
close #{이슈넘버}
<br>
<br>
- 읽지 않은 알림 개수 조회 api 연동 및 퍼블리싱
<br>
- 사원 리스트 행 css 수정

[FEAT] 읽지 않은 알림 개수 조회 api 연동 및 퍼블리싱

---

src/components/AsideComponent.vue
src/services/FinalEvalApi.js
src/views/final-eval/FinalEvalListReadPage.vue

최종평가 프론트 리팩토링
close #400
- 최종평가 프론트 리팩토링

[REFACTOR] 최종평가 프론트 리팩토링

---

src/App.vue
src/components/AsideComponent.vue
src/stores/UserStore.js
src/stores/sse.js

security rtr 관련 리팩토링
<br>
close #402 
<br>
<br>
- security rtr 관련 리팩토링
<br>
-

[REFACTOR] security 관련 리팩토링

---

src/services/OnboardingDataApi.js
src/views/onboarding/OnboardingDataPage.vue

[REFACTOR] 온보딩 설계 리팩토링

---

src/services/OnboardingDataApi.js
src/views/mentoring/MentoringMatchingCreatePage.vue
src/views/onboarding/OnboardingDataPage.vue

[REFACTOR] 퀴즈 카테고리 연동

---

src/App.vue
src/components/AlarmModal.vue
src/components/AsideComponent.vue
src/main.js
src/router/index.js
src/services/OnboardingDataApi.js
src/views/final-eval/FinalEvalDetailReadPage.vue
src/views/mentoring/MentoringMatchingCreatePage.vue
src/views/mentoring/MentoringPlanningDetailPage.vue
src/views/mentoring/MentoringPlanningListPage.vue
src/views/mentoring/report/MentoringReportListPage.vue
src/views/onboarding/OnboardingDataPage.vue
src/views/task-eval/TaskEvalResultListReadPage.vue
src/views/user/LoginPage.vue
src/views/user/hr/views/employee/EmployeeListPage.vue

(담당자 로그인 시) 로그 삭제 및 디테일 수정
<br>
close #406 
<br>
<br>
- (담당자 로그인 시) 로그 삭제 및 디테일 수정
<br>
- aside, onboarding, plan, report 등
- /main 경로 리다이렉트

[REFACTOR] (담당자 로그인 시) 로그 삭제 및 디테일 수정

---

src/App.vue
src/services/WikiApi.js
src/styles/task-eval/TaskEvalResultDetailReadModal.css
src/views/final-eval/FinalEvalDetailReadPage.vue
src/views/task-eval/TaskEvalResultListReadPage.vue
src/views/wiki/WikiCreatePage.vue
src/views/wiki/WikiListReadPage.vue

엘라스틱 서치 인덱스 생성
close #413
- 엘라스틱 서치 인덱스 생성
- CSS 디테일 수정

[REFACTOR] 엘라스틱 서치 인덱스 생성

---

src/services/TaskAddApi.js
src/views/task/TaskAddPage.vue

과제 제출 로직 수정
<br>
close #410 
<br>
<br>
- 
<br>
-

[FIX] 과제 제출 로직 수정

---

src/styles/final-eval/FinalEvalDetailPage.css
src/styles/final-eval/FinalEvalListPage.css
src/styles/task-Ind/TaskIndManage.css
src/views/task-eval/TaskEvalResultListReadPage.vue
src/views/wiki/WikiListReadPage.vue

담당자 로그인 시 화면 CSS 수정 및 로그 삭제
<br>
close #408 
<br>
<br>
- 담당자 로그인 시 화면 CSS 수정 및 로그 삭제
<br>
-

[CHORE] 담당자 로그인 시 화면 CSS 수정 및 로그 삭제

---

src/router/index.js
src/views/user/LoginPage.vue

무한 리다이렉트 수정
<br>
close #415 
<br>
<br>
- 무한 리다이렉트 수정
<br>
-

[FIX] 무한 리다이렉트 수정

---

src/components/AsideComponent.vue
src/router/index.js

팀장 로그인 시 멘토링 메뉴 중복 노출 수정
팀장 로그인 시 멘토링 메뉴 중복 노출 수정<br>
close #418 
<br>
<br>
- aside 팀장, 멘토 멘토링 메뉴 통합 관리
<br>
-

[REFACTOR] 팀장 로그인 시 멘토링 메뉴 중복 노출 수정

---

src/components/AsideComponent.vue
src/components/EmployeeProfile.vue
src/views/mentoring/MentoringPlanningCreatePage.vue
src/views/mentoring/report/MentoringReportDetailPage.vue

팀장, 멘토, 멘티 로그인 시 css, 디테일 수정
팀장, 멘토, 멘티 로그인 시 css, 디테일 수정<br>
close #420 
<br>
<br>
- 팀장, 멘토, 멘티 로그인 시 css, 디테일 수정
<br>
-

[CHORE] 팀장, 멘토, 멘티 로그인 시 css, 디테일 수정

---

src/styles/chatbot/ChatbotCustom.css
src/styles/quiz/HrQuiz.css

close #422
<br>
- 담당자 퀴즈, 챗봇 커스텀 css 리펙토링

[REFACTOR] 담당자 퀴즈, 챗봇 커스텀 css 리펙토링

---

src/components/AsideComponent.vue
src/services/TaskAddApi.js
src/services/TaskListApi.js
src/views/mentoring/MentoringMatchingCreatePage.vue

task 기능 수정
<br>
close #417 
<br>
<br>
- 
<br>
-

[FIX] task 기능 수정

---

src/services/GroupingApi.js
src/views/task/GroupingPage.vue

close #425
<br>
- 공통 과제 매칭
<br>
-

[FIX] 공통 과제 매칭

---

src/App.vue
src/services/ChatApi.js
src/services/MenteeTaskDetailReadApi.js
src/services/MentoringApi.js
src/services/OnBoardingAPI.js
src/services/TaskIndManageApi.js
src/services/TaskListApi.js
src/services/UserApi.js
src/services/WikiApi.js
src/stores/WebSocketStore.js
src/views/chat/Chatting.vue
src/views/mentoring/MentoringPlanningCreatePage.vue
src/views/mentoring/MentoringPlanningListPage.vue
src/views/mentoring/report/MentoringReportDetailPage.vue
src/views/onboarding/ConferenceRoomPage.vue
src/views/onboarding/MainPage.vue
src/views/quiz/QuizPage.vue
src/views/task-eval/TaskEvalResultGroupMembersReadModal.vue
src/views/task/GroupingPage.vue
src/views/user/UpdatePassword.vue

close #427 
<br>
- log 주석처리
<br>
-

[CHORE] log 주석처리

---

src/styles/onboarding/OnboardingData.css
src/styles/user/MenteeOnboardingPage.css
src/views/chat/Chatting.vue
src/views/wiki/WikiDetailReadPage.vue

[REFACTOR] 수정사항
